# -*- coding: utf-8 -*-
import os, json
ROOT="/Users/yuriko/Documents/konnekted-ip"
TODAY="2026-06-16"
reports=json.load(open(os.path.join(ROOT,"reports.json"),encoding="utf-8"))
for r in reports:
    tp=os.path.join(ROOT,r["slug"],"_thumb.txt")
    r["thumb"]=open(tp).read().strip() if os.path.exists(tp) else ""

def esc(s): return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")

CSS='''*{margin:0;padding:0;box-sizing:border-box}
:root{--blue:#4CEDFF;--ink:#0c1726;--paper:#f4f8fc;--card:#fff;--line:#e2ebf3;--mut:#65788c}
body{font-family:"Noto Sans JP",sans-serif;background:var(--paper);color:var(--ink);line-height:1.7;-webkit-text-size-adjust:100%}
.wrap{max-width:980px;margin:0 auto;padding:0 16px 64px}
a{color:#0a93c4}
.hero{background:linear-gradient(135deg,#0a2540,#08406b 55%,#0a93c4);color:#fff;padding:50px 22px 40px;border-radius:0 0 26px 26px;position:relative;overflow:hidden}
.hero:after{content:"";position:absolute;right:-50px;top:-50px;width:240px;height:240px;background:radial-gradient(circle,rgba(76,237,255,.5),transparent 70%)}
.kic{font-size:12px;letter-spacing:.18em;color:var(--blue);font-weight:700}
.hero h1{font-family:"Bebas Neue";font-size:60px;letter-spacing:.04em;line-height:1;margin:6px 0}
.hero p{font-size:14px;opacity:.92;max-width:640px}
.bar{display:flex;flex-wrap:wrap;gap:10px;align-items:center;margin-top:26px}
.bar label{font-size:12px;color:var(--mut)}
.bar select{font-family:inherit;font-size:13px;padding:8px 12px;border:1px solid var(--line);border-radius:10px;background:#fff;color:var(--ink)}
.bar .count{margin-left:auto;font-size:12px;color:var(--mut)}
.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:18px}
.c{display:block;background:#fff;border:1px solid var(--line);border-radius:16px;overflow:hidden;text-decoration:none;color:inherit;box-shadow:0 4px 18px rgba(10,60,107,.06);transition:transform .15s,box-shadow .15s}
.c:hover{transform:translateY(-3px);box-shadow:0 10px 26px rgba(10,60,107,.14)}
.c .ph{aspect-ratio:16/10;background:#dde8f0;position:relative;overflow:hidden}
.c .ph img{width:100%;height:100%;object-fit:cover}
.c .ph .nm{position:absolute;left:14px;bottom:10px;font-family:"Bebas Neue";font-size:34px;color:#fff;letter-spacing:.03em;text-shadow:0 2px 8px rgba(0,0,0,.5)}
.c .ph .ov{position:absolute;inset:0;background:linear-gradient(transparent 45%,rgba(6,16,28,.6))}
.c .b{padding:12px 15px}
.c .type{display:inline-block;font-size:10px;font-weight:700;color:#fff;padding:2px 9px;border-radius:99px}
.c .label{font-size:12px;color:var(--mut);margin-top:7px}
.c .d{font-size:11px;color:#9fb3c6;margin-top:5px}
.empty{grid-column:1/-1;text-align:center;color:var(--mut);font-size:13px;padding:40px}
footer{margin-top:40px;padding:18px;background:#0c1726;color:#9fb3c6;border-radius:16px;font-size:11.5px;text-align:center;line-height:1.8}
footer b{color:#ffd43b}
@media(max-width:780px){.grid{grid-template-columns:1fr 1fr}}
@media(max-width:520px){.grid{grid-template-columns:1fr}.hero h1{font-size:48px}}
'''

H=['<!DOCTYPE html><html lang="ja"><head><meta charset="utf-8">',
 '<meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow">',
 '<title>KONNEKTED ｜ IP提案ブリーフ 目次</title>',
 '<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Noto+Sans+JP:wght@400;700;900&display=swap" rel="stylesheet">',
 '<style>'+CSS+'</style></head><body>']
H.append('<div class="hero"><div class="wrap" style="padding-bottom:0">')
H.append('<div class="kic">KONNEKT ＿ KONNEKTED</div><h1>IP PROPOSAL BRIEF</h1>')
H.append('<p>KONNEKTED（カスタマイズ自社商品）の提案前リサーチ集。メンカラ・年齢・趣味・写真・過去グッズ・提案ヒントを1枚に。所属・名前で絞り込み。</p>')
H.append('</div></div><div class="wrap">')
H.append('<div class="bar"><label>所属</label><select id="fLabel"><option value="">すべて</option></select>')
H.append('<label>種別</label><select id="fType"><option value="">すべて</option></select>')
H.append('<label>並び</label><select id="sort"><option value="name">名前順 (A→Z)</option><option value="date">新着順</option><option value="members">人数順</option></select>')
H.append('<span class="count" id="count"></span></div>')
H.append('<div class="grid" id="grid"></div>')
H.append('<footer><b>社内提案検討用 / 対外配布禁止</b><br>各IPの情報・画像は各公式に帰属します。提案検討のための社内リサーチです。<br>generated by KONNEKT ＿ /ip-brief</footer>')
H.append('</div><script>')
H.append('var REPORTS='+json.dumps(reports,ensure_ascii=False)+';')
H.append(r'''
function uniq(k){var s=[];REPORTS.forEach(function(r){if(s.indexOf(r[k])<0)s.push(r[k]);});return s;}
function fill(id,k){var sel=document.getElementById(id);uniq(k).sort().forEach(function(v){var o=document.createElement('option');o.value=v;o.textContent=v;sel.appendChild(o);});}
fill('fLabel','label');fill('fType','type');
function render(){
  var fl=document.getElementById('fLabel').value,ft=document.getElementById('fType').value,so=document.getElementById('sort').value;
  var list=REPORTS.filter(function(r){return (!fl||r.label===fl)&&(!ft||r.type===ft);});
  list.sort(function(a,b){
    if(so==='name')return a.name.toLowerCase()<b.name.toLowerCase()?-1:1;
    if(so==='date')return a.date<b.date?1:-1;
    if(so==='members')return b.members-a.members;return 0;});
  var g=document.getElementById('grid');g.innerHTML='';
  if(!list.length){g.innerHTML='<div class="empty">該当なし</div>';}
  list.forEach(function(r){
    var a=document.createElement('a');a.className='c';a.href='./'+r.slug+'/';
    var img=r.thumb?'<img src="'+r.thumb+'" alt="'+r.name+'">':'';
    a.innerHTML='<div class="ph">'+img+'<div class="ov"></div><span class="nm">'+r.name+'</span></div>'+
      '<div class="b"><span class="type" style="background:'+(r.accent||'#0a93c4')+'">'+r.type+'</span>'+
      '<div class="label">'+r.label+' ・ '+r.members+'名</div><div class="d">'+r.date+'</div></div>';
    g.appendChild(a);
  });
  document.getElementById('count').textContent=list.length+' 件';
}
['fLabel','fType','sort'].forEach(function(id){document.getElementById(id).addEventListener('change',render);});
render();
''')
H.append('</script></body></html>')
out=os.path.join(ROOT,"index.html")
open(out,"w",encoding="utf-8").write("".join(H))
print("index size:",round(os.path.getsize(out)/1024,1),"KB","| reports:",len(reports))
